# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d474fceb11ac8c72fe67ae6b85a37b559f742182f2d9afd24cdeb3094c3ad527f1d39cf138c545a677a5ec48c73065f24cdd73b9eaca60d5a9cd830397967dad

test:
  secret_key_base: 9eb35068b6a1361ff7db36e253b9b57ce6f0a3203d463f575b022bb866cd1dc506097bd089c6a5e092160c5afe422aff2e09ac5b532d5d6d5d94851101dd4a05

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
